# Generated by Django 4.2.3 on 2023-07-19 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MaxValueValidator(99)]),
            preserve_default=False,
        ),
    ]
